# TODO: repurpose as IR blaster for TV
esphome:
  name: 26-c3u-bt-proxy
  friendly_name: 26 Bluetooth Proxy
  platformio_options:
    board_build.flash_mode: dio
  includes:
    - util.h

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n

# Enable logging
logger:
  level: DEBUG

ota:
- platform: esphome
  id: my_ota

api:

wifi:
  ssid: "kni"
  password: !secret kni_pw
  manual_ip:
    # Choose by running "make ips"
    static_ip: 192.168.85.26
    gateway: 192.168.84.254
    subnet: 255.255.240.0
    dns1: 192.168.84.1

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true
