esphome:
  name: c3-acurite-986-bridge
  includes:
    - custom/acurite-00986.h
  platformio_options:
    board_build.flash_mode: dio

esp32:
  # Actually an m5stamp C3U
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

ota:

wifi:
  ssid: "kni"
  password: !secret kni_pw
  manual_ip:
    # Choose by running "make ips"
    static_ip: 192.168.85.26
    gateway: 192.168.84.254
    subnet: 255.255.240.0
    dns1: 192.168.84.1


time:
  - platform: sntp
    id: my_time

mqtt:
  broker: !secret mqtt_office_broker
  username: !secret mqtt_office_user
  password: !secret mqtt_office_pw

custom_component:
  - lambda: |-
      auto acurite_component = new Acurite00986Component(GPIO_NUM_4, "sensors/acurite-986-");
      App.register_component(acurite_component);
      return {acurite_component};
