version: "3.8"
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - config:/mosquitto/config
      - data:/mosquitto/data
      - log:/mosquitto/log
  exporter:
    image: sapcc/mosquitto-exporter
    ports:
      - 9234:9234
    environment:
      - BROKER_ENDPOINT=tcp://broker:1883
      - MQTT_CLIENT_ID=exporter

volumes:
  config:
  data:
  log:
