esphome:
  name: m5stick-c1
  platform: ESP32
  board: m5stick-c
  on_boot:
    then:
      - light.turn_on:
          id: red_led
          brightness: 5%

# Enable logging
logger:
  level: INFO

ota:
  password: ""

mqtt:
  broker: kelvie-lws.lan
  username: m5stickc1
  password: !secret mqtt_m5stickc1_pw

wifi:
  ssid: "kni"
  password: !secret kni_pw

binary_sensor:
  - platform: gpio
    id: button1
    pin:
      number: GPIO37
      inverted: true
    filters:
      delayed_off: 30ms
    on_release:
      then:
        - mqtt.publish:
            topic: m5stick-c/button1
            payload: ding

  - platform: gpio
    id: button2
    pin:
      number: GPIO39
      inverted: true
    filters:
      delayed_off: 30ms
    on_release:
      then:
        - mqtt.publish:
            topic: office/usbswitch
            payload: click

output:
  - platform: ledc
    pin:
      number: GPIO10
      inverted: true
    id: gpio_10

light:
  - platform: monochromatic
    output: gpio_10
    id: red_led
