
esphome:
  name: nanlink-control
  platform: ESP32
  board: esp32dev
  libraries:
    - rf24
  includes:
    - util.h
    - rf24-nanlink.h

spi:
  clk_pin: GPIO22
  mosi_pin: GPIO23
  miso_pin: GPIO19
#  cs_pin: GPIO33
#  ce_pin: GPIO21

# Enable logging
logger:
  level: DEBUG

ota:
  password: ""

mqtt:
  broker: !secret mqtt_office_broker
  username: !secret mqtt_office_user
  password: !secret mqtt_office_pw

wifi:
  ssid: "kni"
  password: !secret kni_pw

custom_component:
  - lambda: |-
      return {new RF24NanlinkSpiComponent};
    components:
      - id: nanlink_rf24
        # cs_pin: GPIO33
