esphome:
  name: office
  platform: ESP32
  board: esp32dev # actually an m5stack ATOM lite
  libraries:
    - rf24
  includes:
    - rf24-nanlink.h

spi:
  clk_pin: GPIO22
  mosi_pin: GPIO23
  miso_pin: GPIO19

# Enable logging
logger:
  level: DEBUG

ota:
  password: ""

wifi:
  ssid: "kni"
  password: !secret kni_pw

mqtt:
  broker: kelvie-lws.lan
  username: office
  password: !secret mqtt_office_pw

custom_component:
  - lambda: |-
      return {new RF24NanlinkSpiComponent};
    components:
      - id: nanlink_rf24
        # cs_pin: GPIO33
