esphome:
  name: office-atom-neokey
  platform: ESP32
  board: esp32dev # actually an m5stack ATOM lite

# Enable logging
logger:
  level: DEBUG

ota:
  password: ""

wifi:
  ssid: "kni"
  password: !secret kni_pw
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.85.12
    gateway: 192.168.84.1
    subnet: 255.255.240.0
    dns1: 192.168.94.1

mqtt:
  broker: !secret mqtt_office_broker
  username: !secret mqtt_office_user
  password: !secret mqtt_office_pw


binary_sensor:
  - platform: gpio
    pin:
      number: 33
      mode: INPUT_PULLUP
      inverted: True
    id: neo4
    filters: &button_filters
      delayed_on_off: 40ms
    on_click: &click_defaults
      min_length: 50ms
      then:
        - mqtt.publish:
            topic: office/super # super ends
            payload: ding

  - platform: gpio
    pin:
      number: 19
      mode: INPUT_PULLUP
      inverted: True
    id: neo2
    filters:
      <<: *button_filters
    on_click:
      <<: *click_defaults
      then:
        - mqtt.publish:
            topic: nanlink/ch4
            payload: dim_up 5

    on_double_click: &doubleclick_defaults
      min_length: 20ms
      max_length: 150ms
      then:
        - mqtt.publish:
            topic: nanlink/ch4
            # this actually gets it to 50 cause it also queues up two clicks
            payload: dim_up 40

  - platform: gpio
    pin:
      number: 23
      mode: INPUT_PULLUP
      inverted: True
    id: neo3
    filters:
      <<: *button_filters
    on_click:
      <<: *click_defaults
      then:
        - mqtt.publish:
            topic: nanlink/ch4
            payload: dim_down 5

    on_double_click:
      <<: *doubleclick_defaults
      then:
        - mqtt.publish:
            topic: nanlink/ch4
            payload: dim_down 120

  - platform: gpio
    pin:
      number: 22
      mode: INPUT_PULLUP
      inverted: True
    id: neo1
    filters:
      <<: *button_filters
    on_double_click:
      <<: *doubleclick_defaults
      then:
        - mqtt.publish:
            topic: office/monitor/restart
            payload: ding
