
esphome:
  name: office-control-deck
  platform: ESP32
  board: esp32dev # use m5stack atom for now
  libraries:
    - SPI
    - Wire
    - adafruit/Adafruit BusIO
    - adafruit/Adafruit seesaw Library
  includes:
    - neokey.h

# Enable logging
logger:
  level: INFO

ota:
  password: ""

# Right side pins
i2c:
  sda: 25
  scl: 21
  scan: true

mqtt:
  broker: kelvie-lws.lan
  username: office
  password: !secret mqtt_office_pw
  id: mqtt_client

binary_sensor:
  - platform: template
    id: button1
    filters:
      delayed_off: 30ms
    on_release:
      then:
        - mqtt.publish:
            topic: nanlink/ch4
            payload: dim_up 120
  - platform: template
    id: button2
    filters:
      delayed_off: 30ms
    on_release:
      then:
        - mqtt.publish:
            topic: nanlink/ch4
            payload: dim_up 5
  - platform: template
    id: button3
    filters:
      delayed_off: 30ms
    on_release:
      then:
        - mqtt.publish:
            topic: nanlink/ch4
            payload: dim_down 5
  - platform: template
    id: button4
    filters:
      delayed_off: 30ms
    on_release:
      then:
        - mqtt.publish:
            topic: nanlink/ch4
            payload: dim_down 120

wifi:
  ssid: "kni"
  password: !secret kni_pw

custom_component:
  - lambda: |-
      return {new NeoKey1x4Component(
          0xFFFFFF, id(button1), id(button2), id(button3), id(button4))};
    components:
      - id: neokey1x4
