esphome:
  name: office
  platform: ESP32
  board: esp32dev # actually an m5stack ATOM lite
  libraries:
    - SPI
    - rf24
  includes:
    - rf24-nanlink.h

spi:
  clk_pin: GPIO22
  mosi_pin: GPIO23
  miso_pin: GPIO19

# Enable logging
logger:
  level: DEBUG

ota:
  password: ""

wifi:
  ssid: "kni"
  password: !secret kni_pw
  manual_ip:
    static_ip: 192.168.85.11
    gateway: 192.168.84.1
    subnet: 255.255.240.0
    dns1: 192.168.94.1

mqtt:
  broker: !secret mqtt_office_broker
  username: !secret mqtt_office_user
  password: !secret mqtt_office_pw

custom_component:
  - lambda: |-
      return {new RF24NanlinkSpiComponent};
    components:
      - id: nanlink_rf24
        # cs_pin: GPIO33
