esphome:
  name: office-usb-switcher-desk-atom
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  level: DEBUG

ota:
  password: ""

mqtt:
  broker: !secret mqtt_office_broker
  username: !secret mqtt_office_user
  password: !secret mqtt_office_pw
  on_message:
    - topic: office/usbswitch
      then:
        - switch.turn_on: usbswitch

wifi:
  ssid: "kni"
  password: !secret kni_pw

switch:
  - platform: gpio
    id: usbswitch
    pin:
      number: GPIO25
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: usbswitch

binary_sensor:
  - platform: gpio
    id: button1
    pin:
      number: GPIO39
      inverted: true
    filters:
      delayed_off: 30ms
    on_release:
      then:
        - switch.turn_on: usbswitch
