# Basic Config
esphome:
  name: sonoff-s31-5
esp8266:
  board: esp01_1m
wifi:
  ssid: "kni"
  password: !secret kni_pw
  manual_ip:
    static_ip: 192.168.85.20
    gateway: 192.168.84.254
    subnet: 255.255.240.0
    dns1: 192.168.84.1
mqtt:
  broker: !secret mqtt_office_broker
  username: !secret mqtt_office_user
  password: !secret mqtt_office_pw
logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
ota:
  - platform: esphome
# Device Specific Config

# counters sometimes get stuck, fix this by restarting every day
button:
  - platform: restart
    name: Restart
    id: restart_button
substitutions:
  energy_update_interval: 5s
uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S31 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S31 Status"
sensor:
  - platform: wifi_signal
    name: "Sonoff S31 WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "Sonoff S31 Current"
      accuracy_decimals: 4
      id: my_current
      filters:
        - throttle_average: ${energy_update_interval}
    voltage:
      name: "Sonoff S31 Voltage"
      accuracy_decimals: 1
      id: my_voltage
      filters:
        - throttle_average: ${energy_update_interval}
    power:
      name: "Sonoff S31 Power"
      accuracy_decimals: 2
      id: my_power
      filters:
        - throttle_average: ${energy_update_interval}
    energy:
      name: "Sonoff S31 Total energy"
      id: my_energy
      filters:
        - throttle_average: ${energy_update_interval}
  - platform: total_daily_energy
    name: "Sonoff S31 Daily Energy"
    power_id: my_power
interval:
  - interval: 5s
    then:
      - mqtt.publish_json:
          topic: sensors/sonoff-s31-5
          payload: !lambda |-
            root["power_w"] = id(my_power).state;
            root["current_a"] = id(my_current).state;
            root["voltage_v"] = id(my_voltage).state;
            root["energy_wh"] = id(my_energy).state;
switch:
  - platform: gpio
    name: "Sonoff S31 Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON
time:
  - platform: sntp
    id: my_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - button.press: restart_button
status_led:
  pin: GPIO13
